### ISSUE TITLE
Include settings/option in Backup / Restore

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#176]
We should include the plugin settings in the Backup / Restore feature.

It is possible for people to cause issues on their site if they change a setting such as changing the settings to turn on "Type-Specific Capabilities"

**Comment by agapetry** [comment]
I think the settings backup / restore should be a separate operation.  In some cases, it would be better to restore a previous set of capabilities while keeping the same settings.

**Comment by stevejburge** [comment]
@agapetry Interesting, thanks. 

Would it be a pain to manage 2 backups, and then 2 import / exports?

**Comment by agapetry** [comment]
The inner workings of the settings backup will be different anyway (multiple wp_options rows to back up instead of a single roles row).  We can trigger auto-backups at the same time, but on the Restore Tab have separate sections:

![image](https://user-images.githubusercontent.com/43488774/124148891-19d36f00-da5e-11eb-8dac-a72d4d1a7d88.png)

![image](https://user-images.githubusercontent.com/43488774/124149828-f65cf400-da5e-11eb-8184-2c1c83e6189d.png)

If you want, there could be a default-selected option to restore both roles and corresponding settings (if they were both backed up at the same time).  But I think there should be an ability to restore one without the other.

**Comment by stevejburge** [comment]
@agapetry @olatechpro OK, let's try that, please

**Comment by olatechpro** [comment]
@stevejburge i'm just seeing this while checking the milestone to be sure no pending issue.

The problem with having this as a separate issue is the import/export PR is still opened and since development is the base, no way to work this on a separate PR. So until the import/export is merged to development, should we close this and make the commit on opened import and export PR https://github.com/publishpress/PublishPress-Capabilities/pull/288 or wait till it's merged ?

**Comment by olatechpro** [comment]
Pro PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/99

**Comment by olatechpro** [comment]
This been merged/released
