### ISSUE TITLE
More Columns on Roles Screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#181]
Let's add columns for "Capabilities", "Editor Features", "Admin Menus", "Nav Menus" that would:

- Count the total number of those restrictions for the role
- Link to the corresponding Restrictions screen, loading that role

We could also add "type". 

Here's an example:
<img width="1137" alt="Screen Shot 2021-07-08 at 12 24 35 PM" src="https://user-images.githubusercontent.com/3868028/124957830-7f3bd880-dfe7-11eb-9efb-1089a77d915a.png">

One more example:
<img width="1238" alt="Screen Shot 2021-07-08 at 12 25 04 PM" src="https://user-images.githubusercontent.com/3868028/124957870-8c58c780-dfe7-11eb-8afc-ba848a5d57be.png">

**Comment by olatechpro** [comment]
@stevejburge don't you think adding "Type" role is same thing as repeating what we already have at the top?
1.) WordPress => Built-In.
2.) Custom => Other roles

If we plan on improving the role screen to link to other pages and features, that shows the screen will be busy in the long run and perhaps, we should add necessary column rather than repetitive column or this is really important?

**Comment by olatechpro** [comment]
@stevejburge in addition, features like "Nav Menus" for example are pro only. So, should we exclude such column if user is using free version or we should add for all?

**Comment by olatechpro** [comment]
This has been merged
