### ISSUE TITLE
PHP Notice: Undefined index: action

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#237]
`[02-Nov-2021 09:42:57 UTC] PHP Notice: Undefined index: action in /public_html/wp-content/plugins/capability-manager-enhanced/includes/admin-load.php on line 61`

https://wordpress.org/support/topic/there-is-an-error-8/

**Comment by agapetry** [comment]
@stevejburge I don't think this can be happening in the current release.  The line number isn't right.

**Comment by agapetry** [comment]
This is mostly a nothing burger because an Ajax request without an action argument is invalid and ineffective, immediately terminated by Wordpress:

![image](https://user-images.githubusercontent.com/43488774/140076451-90124417-2f11-486e-a7c6-a4f72bcc55f3.png)

However, the user pointed out that a malicious externally generated admin-ajax.php request can cause this error.  In other words, we fix this to prevent hackers from loading PHP error logs with this notice.
