### ISSUE TITLE
How to deal with Classic Editor / Gutenberg etc switch

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#258]
We now support multiple post types with "Editor Features".

Can we allow users to select one of three choices for each post type?

- Gutenberg
- Classic Editor
- Disable

At the moment, you have to install the Classic Editor plugin in order to use "Editor Features" with post types such as Easy Digital Downloads

**Comment by agapetry** [comment]
@stevejburge There is already a constant definition available for this:

`define('PP_CAPABILITIES_CONFIGURE_CLASSIC_EDITOR', true);`

In addition, WooCommerce activation automatically forces Classic Editor tab availability on the Editor Features configuration screen.

**Comment by stevejburge** [comment]
Thanks. Maybe it's a UI issue?

At the moment, here's what happens if you're using Easy Digital Downloads:

- You need to install Classic Editor
- You need to change the Classic Editor settings so that the Block Editor is the default
- You need to ignore the "Gutenberg" options for Easy Digital Downloads

I think if we make this change, we can have an easier option for each post type:
https://github.com/publishpress/PublishPress-Capabilities/issues/257

**Comment by agapetry** [comment]
No, it's a switch you have to turn on by putting that define statement into wp-config.php. Temporary measure added right before 2.3.2 release.

**Comment by stevejburge** [comment]
@agapetry Can make this available to users in the UI so they don't need wp-config.php?

**Comment by agapetry** [comment]
Yes, the define statement was only intended as a temporary measure to avoid delaying release.

**Comment by stevejburge** [comment]
OK, thanks. @olatechpro 

Can we make this easier in the UI? I think the best approach is one choice for each post type:

Can we allow users to select one of three choices for each post type?

- Gutenberg
- Classic Editor
- Disable (this is the default)

**Comment by olatechpro** [comment]
@stevejburge for the disable tab, what's will the tab content, is it combination of all options under Gutenberg and Classic Editor or only options under 'Classic Editor' since we're doing this purposely for classic editor options for cpt that uses it or i'm i missing something ?

**Comment by stevejburge** [comment]
@olatechpro Good question. Maybe the best approach is to wait to see the result of this first: https://publishpress.com/blog/series/publishpress-series-271/

**Comment by olatechpro** [comment]
No problem @stevejburge

**Comment by olatechpro** [comment]
@stevejburge , what's the final conclusion on this ?

**Comment by stevejburge** [comment]
@olatechpro I think this is the best approach, please:
https://github.com/publishpress/PublishPress-Capabilities/issues/258#issuecomment-991267529

Post Types are vertical. 
Classic / Gutenberg etc are horizontal tabs

**Comment by olatechpro** [comment]
@stevejburge , i read over the comments again and still doesn't get answer for my last question on the tabs or maybe your new resolution,

You currently asked us to have the following tabs:
- Gutenberg
- Classic Editor
- Disable

We already have 'Gutenberg' and 'Classic Editor' tabs and my last question was what'll be the content on the newly introduced 'Disable' tabs ?

- On the linked comment https://github.com/publishpress/PublishPress-Capabilities/issues/258#issuecomment-991267529 . Clicking it does not scroll to any comment, so, i didn't know what you're trying to reference but the short comments read:

>  Post Types are vertical.
> Classic / Gutenberg etc are horizontal tabs

which is not explanatory enough for me to know the relation.

Will be glad if you can be explicit with this issue requirement just incase it changes due to the conversation above as right now, what i understand is the three tabs requests which prompt me to ask for the content of disable that and reading over and over again, i don't see how it relate with Post types.

**Comment by olatechpro** [comment]
@stevejburge this issue already move to https://github.com/publishpress/PublishPress-Capabilities/issues/257
