### ISSUE TITLE
Not picking up the "Templates" panel

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#309]
At the moment, "Editor Features" isn't able to pick up the "Templates" metabox that is part of the WordPress core (although it only shows if you have a theme that supports it)

<img width="633" alt="Screen Shot 2022-02-28 at 10 29 50 AM" src="https://user-images.githubusercontent.com/3868028/156010491-eb282e0b-b6ca-46d2-937d-6b4e4dfc1aa3.png">

**Comment by olatechpro** [comment]
@stevejburge template was part of Post Attribute in previous releases of WordPress, i think they just introduced it as a separate metabox to Gutenberg and it's not available through PHP function that return metabox(missing from the result) which makes me believe it could rendered via react and as a result, i'll simply add this manually to the list of metabox

**Comment by olatechpro** [comment]
@stevejburge , after reviewing it again and related code in relation to it been Gutenberg element, the template was added as a Panel and not a metabox and i think that explains why it wasn't present in list of metabox. 

So, i'll be adding this to "Document Panel" section and not metabox because it's not a metabox
