### ISSUE TITLE
Problem with redirection scripts

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#313]
I think @olatechpro is on top of this one.

A customer is using LoginWP (Formerly Peter's Login Redirect) to send contributors directly to the list of posts rather than the wp dashboard welcome screen
<img width="1627" alt="Screenshot 2022-02-23 at 13 05 21" src="https://user-images.githubusercontent.com/3868028/156804811-5b727605-001d-4646-a434-674a2f6c809a.png">

Ola's comment:

> In capabilities, we echo (added) a style element hooking to admin_head which is fair
> So, any plugin or action trying to redirect user should do that in init or admin_init
> It’s normal for a plugin to output content in admin head
> but if this is causing issue, then i can check if moving the element to admin footer won’t have any issue and if not, i can change the feature restriction implementation code to admin_footer instead

**Comment by agapetry** [comment]
@olatechpro 

It looks like our code is executing on the 'init' action:
`
add_action('init', [$this, 'featureRestrictionsGutenberg']);`

Does this need to be loaded more selectively to avoid conflicts like this?

**Comment by olatechpro** [comment]
Yes @agapetry and @stevejburge i think you added this to 3.3.5 after i completed work on it and as a result, not aware it's in 2.3.5. 

So, i modified the milestone and move it to the milestone i'm currently working on but if you still need it to be in 2.3.5, i can pause 2.4 milestone and have a look at this first since it's the next milestone in release?

**Comment by stevejburge** [comment]
@olatechpro Yes, please. Let's work on this now and release this one quickly

**Comment by olatechpro** [comment]
Got it
