### ISSUE TITLE
Include a sucess message for key tasks on "Roles" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#366]
In previous versions of Capabilities we had a success message after deleting / creating / copying roles

Let's bring those back to the Role screen. If someone has made a change, let's show a confirmation message

<img width="472" alt="role-moved-to-subscriber" src="https://user-images.githubusercontent.com/3868028/163596394-e9e1afad-ed52-4e0b-b50d-574923594646.png">

**Comment by olatechpro** [comment]
@stevejburge when roles are added, copied or deleted. We show response status message after each action.

I’m wondering if issues is meant for something else as we output notification message for every role action

**Comment by stevejburge** [comment]
Hi @olatechpro 

I'm not seeing that in the Roles screen. We do have the OK option, but after that ... no message
<img width="506" alt="Screen Shot 2022-04-15 at 12 39 18 PM" src="https://user-images.githubusercontent.com/3868028/163597125-ac21519c-9bf7-4e00-9af1-40cf2a6acfc7.png">

**Comment by stevejburge** [comment]
@olatechpro I think we do a better job of this when editing roles. For example, this is great:
<img width="791" alt="Screen Shot 2022-04-15 at 12 43 52 PM" src="https://user-images.githubusercontent.com/3868028/163597586-af8cfb3e-2c9d-4a57-a1ae-03a46d8e6b4e.png">

**Comment by olatechpro** [comment]
Well, i believe the issue is confusing.

1.) When you create new role, you'll receive notification
2.) When you copy.edit a role, you'll receive notification
3.) When you copy a role, you'll receive notification
4.) When you delete a role either via the role edit screen or bulk edit, that involve page redirecting, you'll receive notification

The only exception is when you delete a single role that we handle via ajax action which the action result is clear to user as the item is highlighted in red then deleted with no page reload and this action can be done at any page. So, that's why i don't see the need for outputting a message which the user may not even see if they're not on top of the page.


Of course, if you want it otherwise, it's okay but the issue is convincing and i was dumbfolded and had to test again when it says ```
In previous versions of Capabilities we had a success message after deleting / creating / copying roles

Let's bring those back to the Role screen. If someone has made a change, let's show a confirmation message
``` as that simply implies notification is broken.

With that been said, i'll output message even when delete action is handled by ajax since the request is clear now.

**Comment by stevejburge** [comment]
OK, thanks @olatechpro. That make sense. Let's close this for now and reopen it only if any users are confused
