### ISSUE TITLE
Admin Menus issue with JetPack

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#381]
The Jetpack plugin is proving difficult to hide, even for Subscribers

It doesn't want to work with either Admin Menus or Admin Features
![Screen Shot 2022-04-22 at 3 21 49 PM](https://user-images.githubusercontent.com/3868028/164782707-3c3ff6fb-e9f8-4bba-9eca-ad24357de11f.png)

**Comment by olatechpro** [comment]
@stevejburge this need to be separated into two issue as admin menu is Pro only features while admin features is both free and pro features.

So, packing the two issues in one is not efficient and  i'm renaming this issue while creating another one for admin features.

**Comment by stevejburge** [comment]
Thanks @olatechpro

**Comment by olatechpro** [comment]
### DEVELOPER NOTE:

I'm dropping this note here for future references purpose.

To fix this, we need to run the admin menus restriction on '999' as jetpack is adding their menu on '998' priority i think due to a conflict with a plugin integration(which i can't remember now), we run this on the hook of 99 but will change it back to 999 now and leave this for reference to why we need to run the restriction on 999.

If any reasons surfaces later to why we need to run the hook on a lower priority, i think we may need to resort to hiding jetpack menu using javascript solution.

**Comment by olatechpro** [comment]
Pro PR https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/125
