### ISSUE TITLE
Admin Menus issue with Yoast

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#493]
Yoast shows some odd behavior with Admin Menus.

For the "SEO Editor" role, it's impossible to hide these menus:
<img width="362" alt="Screen Shot 2022-06-17 at 11 30 37 AM" src="https://user-images.githubusercontent.com/3868028/174330107-7e2cbe16-ad84-4a26-b23c-596a5282ba13.png">

That happens even with all boxes checked:
<img width="425" alt="Screen Shot 2022-06-17 at 11 32 39 AM" src="https://user-images.githubusercontent.com/3868028/174330321-ce113591-4d69-4958-824b-3508d1b6c309.png">

And sometimes when you check all the boxes, most of them disappear:

<img width="344" alt="Screen Shot 2022-06-17 at 11 33 01 AM" src="https://user-images.githubusercontent.com/3868028/174330370-34ba9e65-29ac-4aa3-badd-7dafee4bea8f.png">

**Comment by olatechpro** [comment]
@stevejburge this type of issue happen with plugin that maintain different menu for different roles.

By default, we're using current user menu to show list of menu to be hidden/remove for all roles thereby resulting in this and similar issues previously reported which happen due to different menu position/index and in relation to this specific issue, it happens because Yoast seo menu for administrator is different from editor which i believe is your test case. 

Maybe it's time to only find a workable solution to loading current editing role menu instead of using current user menu in most cases which is admin but i'm not sure how easy this will be and will spend time trying to find a working solution or update on whatever the outcome is.

**Comment by stevejburge** [comment]
Thanks @olatechpro 

If it's difficult and will take some time, we can move this to a future milestone

**Comment by olatechpro** [comment]
So, more update on the origin of the issue.

For administrator role, Yoast SEO for example added a menu '`wpseo_dashboard`' and then added all other submenu but when it come to editor role, the plugin added '`wpseo_workouts`' menu and the applicable sub menu was added and that's the reason we're having this issue.

My initial intention is to save different menu for different roles but while at it, i realised this will cost us more and we'll need to be saving menu every time a dashboard is access and at the same time, we'll have to remove the clause of `manage_capabilities` check before updating menu since the role we're saving the menu may not have the capability.

So, that shows this route route is too expensive for the issue and as a result, I'll include the different variation of Yoast SEO menu slug so if one is blocked, it means the others will be blocked too since it differ by role.

Same solution may be applied to any other plugins with similar implementation when we receive any report for their menu.

@stevejburge @htmgarcia

**Comment by olatechpro** [comment]
@agapetry Pro PRO https://github.com/publishpress/PublishPress-Capabilities-Pro/pull/148

@stevejburge the solution i'm able to apply for this without affecting other roles application is the need to disable main `Yoast menu` for the other roles that doesn't have complete menu

For example, Checking "`Yoast SEO`" for Editors will now remove the Menu for the role fixing the issue but specifically checking just "`Workouts`" and "`Redirects`" won't work as menu position and slug differ and i couldn't apply the position check as it may affect other roles with complete menu. So, for roles without complete menu, there's be need to check parent menu and not sub menu to remove the menu.

So, this fix only made sure Yoast SEO is removed for all roles in as much the main Yoast SEO is checked.

**Comment by stevejburge** [comment]
Thanks for digging into this @olatechpro 

Yes, I'm sure we do need custom solutions like this for some plugins.

I can add this detail to our documentation.

**Comment by olatechpro** [comment]
### I'm adding the below note from https://secure.helpscout.net/conversation/2133082070/175433/  ticket for future reference:

The problem is because the plugin uses a different position for their menu and we're using administrator menu data for the restriction.

So, when plugin added different options for different roles as sub menu, it became difficult to work on unless the whole menu is restricted.

However, there are custom solution available for this type of issue are they are explained below:

1. Add the menu url you want to remove (e.g: /wp-admin/admin.php?page=dhlpwc-menu-link) to "Admin Features" Blocked By Url option to block access to the URL for the role if the role can still access the page but in my test, the user in the selected roles cannot access the page already. So, we only need to deal with step two.

2. Add the sub menu css ID/class to "Admin Features" Hide CSS Element to hide the menu item, the CSS can be seen by inspecting the menu element and in this case, here's each menu css to be added for the affected role.

For example, `#toplevel_page_woocommerce ul li:nth-child(1)` will hide the first submenu child and `#toplevel_page_woocommerce ul li:nth-child(2)` will head the second sub menu. So, the number 1 can be replace with the submenu position and that'll work

**Comment by olatechpro** [comment]
### I'm adding the below note from https://secure.helpscout.net/conversation/2133082070/175433/  ticket for future reference:

The problem is because the plugin uses a different position for their menu and we're using administrator menu data for the restriction.

So, when plugin added different options for different roles as sub menu, it became difficult to work on unless the whole menu is restricted.

However, there are custom solution available for this type of issue are they are explained below:

1. Add the menu url you want to remove (e.g: /wp-admin/admin.php?page=dhlpwc-menu-link) to "Admin Features" Blocked By Url option to block access to the URL for the role if the role can still access the page but in my test, the user in the selected roles cannot access the page already. So, we only need to deal with step two.

2. Add the sub menu css ID/class to "Admin Features" Hide CSS Element to hide the menu item, the CSS can be seen by inspecting the menu element and in this case, here's each menu css to be added for the affected role.

For example, `#toplevel_page_woocommerce ul li:nth-child(1)` will hide the first submenu child and `#toplevel_page_woocommerce ul li:nth-child(2)` will head the second sub menu. So, the number 1 can be replace with the submenu position and that'll work

@stevejburge If we have documentation on this according to your last comment on this issue, then this solution will fit in and may help others facing such issue.

**Comment by rizaardiyanto1412** [comment]
I can write the doc if it has not been created @stevejburge
