### ISSUE TITLE
Can we add support for MetaSlider on the "Capabilities" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#499]
https://wordpress.org/plugins/ml-slider/

**Comment by olatechpro** [comment]
@steve the best way to support a plugin that we have access to their developers is to encourage them to add support for their capabilities tab through the plugin itself.

That way, the plugin capabilities will always be updated and that's what most capabilities plugin does. The plugin tab that exists for them are added by each plugin owner and we made provision for that as well.

Adding it ourselves should be the last resort and reasons we should only do that for plugins we couldn't make the developer do so for.

But if this is the path you want us to go for every plugins, then no problem. 

I'll search the plugin for it capabilities and add the tab.

**Comment by stevejburge** [comment]
Thanks @olatechpro 

I guess I'm thinking two things:

1) Can we scale this without asking developers to support us?
2) Is there documentation we can provide to help developers?

**Comment by stevejburge** [comment]
Thanks @olatechpro 

MetaSlider is one of ours and @andergmartins can help

Maybe let's talk with @agapetry about creating documentation.

**Comment by olatechpro** [comment]
@stevejburge If you want to take my suggestion, the issue shouldn't be here or in current capabilities active milestone. 

...but that's not even the issue, decided to work on it now since it's still on the active milestone and i couldn't find any custom capabilities added by the plugin which shows nothing needed to be done here or you may link me to documentation if otherwise but so far, i searched the plugin codes and no custom capability.
