### ISSUE TITLE
Develop a "Frontend Features" screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#649]
We had a request to hide these Elementor links that only appear on the frontend when looking at a post that uses Elementor.

Can we hide these using an options box, or CSS?

<img width="893" alt="Screen Shot 2022-12-08 at 1 01 02 PM" src="https://user-images.githubusercontent.com/3868028/206529900-589a7ade-26ce-4366-8729-c3ac5a7a76fb.png">

**Comment by stevejburge** [comment]
I wonder if, in the future, we could build a frontend version of "Admin Features" to hide features on the frontend?

**Comment by olatechpro** [comment]
@stevejburge  Admin toolbar is already included in Admin features and it covers both frontend and backend.

The reason the "Edit with Elementor" is not showing in the toolbar list is because it's a conditional toolbar that only appear on pages and we're opened to options on how to handle such issues which are:

1. Do we want to spend more time at looking at possibility of including such toolbar that are not general toolbar but conditional toolbar so they can appear in Admin Features?
2. Easiest fix for this is allowing Admin Feature "Hide CSS Element" to run in frontend as well and that way, issue like this can simply be fixed by adding #wp-admin-bar-elementor_edit_page to the css custom box but I'm still concern about the fact the feature name read "Admin Features" which shows it's an admin settings
3. What other proposal or mode of implementation do you have on mind for this kind of issue since it's not elementor issue alone but editors or plugins that add toolbar that's not global.

**Comment by stevejburge** [comment]
Thanks @olatechpro. I appreciate you breaking this down in such detail.

I wonder if this is could be the start of a new feature: Frontend Features. We could allow users to hide CSS elements on the frontend of their site.

**Comment by stevejburge** [comment]
Thanks. I can see quite a few uses for this. I'm sure users have many things that they want to hide on the frontend of websites.
