### ISSUE TITLE
Update profile items | Update personal profile items 

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#655]
What's the difference here? Should we explain this more clearly?

Update profile items vs Update personal profile items 

I see this explanation:
"I added 2 buttons with first one redirect admin to the current role profile edit screen to enable us retrieve all the profile fields and element for update while the second one redirect to the current user profile fields since profile fields items may differ by roles, users or when editing own profile to when editing others profile"

Can we combine this into one link?
<img width="415" alt="Screen Shot 2023-01-12 at 11 08 38 AM" src="https://user-images.githubusercontent.com/3868028/212119952-5a4b6f2f-3427-409a-b8e8-d83a226efce3.png">

**Comment by olatechpro** [comment]
@stevejburge Maybe it need to be somewhere else considering the fact that position can't take description unless we add title or tooltip?

![rl](https://user-images.githubusercontent.com/46832636/212122584-8ea75f92-3316-4d10-8c9d-dd2624f14038.jpg)
                                      

1. The first title should be "Update **Administrator** profile items" where Administrator is the role that's currently selected on the screen, this allows redirect to a random user edit screen in the role but the reason the Administrator is missing for you is because you probably select a role without user in your user list and as a result, it fallback to your user ID. In real use case, wondering if that'll happen because why will someone modify screen for user base that doesn't exist? Or user in selected role exist but wasn't working for you? 
2. The "Update personal profile items" does exactly what it says, it redirect to editing profile edit screen to enable capturing elements on the screen that only appear when user is editing personal profile. Both button are useful since how profile edit screen looks differ for when editing own profile to when editing other user profile

**Comment by stevejburge** [comment]
@olatechpro Thanks for the details. Can we enable these to run in the background without requiring a click?

**Comment by olatechpro** [comment]
@stevejburge We can't run it in background as there's need to visit profile page to capture the elements on the screen and reason i added a customised link on the page so we don't run the action every time a profile page visit is done.

However, it's possible to remove the link if we decided to be running the function every time profile page visit is done.

Is that okay?

**Comment by stevejburge** [comment]
@olatechpro Good question. I think it will be too much overhead if we run our function every time someone visits a profile page?

Maybe we do just need to keep these links.

Perhaps the best option is a box in the sidebar with an explanation: "Click these links if any items from the Profile screen are missing."

**Comment by stevejburge** [comment]
@olatechpro Could we try a separate box for this please?

Title: Update Profile Features
Text: Click these links if any items from the Profile screen are missing:
Link: Click to update items for this role. 
Link: Click to update items for all roles.

**Comment by olatechpro** [comment]
@stevejburge Please read my comment again on https://github.com/publishpress/PublishPress-Capabilities/issues/655#issuecomment-1380669748 and update new phrase.

It's impossible to update all roles once. So, your new link caption on "Click to update items for all roles" is misleading or will later lead to bugs report of it not doing the work.

**Comment by olatechpro** [comment]
@stevejburge I'm not able to send update on profile feature screen as i was waiting on your response on this.

Kindly check it so I can make update tomorrow

**Comment by stevejburge** [comment]
@olatechpro Sorry, I posted a question in Slack
