### ISSUE TITLE
Don't indent Toggle All

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#657]
I understand why Toggle All is indented here, but to make it consistent with other screens, let's remove the indent:

<img width="413" alt="Screen Shot 2023-01-13 at 11 25 34 AM" src="https://user-images.githubusercontent.com/3868028/212369744-8725c4f3-e2b4-41ca-8e97-d03509ff5d9d.png">

**Comment by olatechpro** [comment]
@FYI, toggle is not indented and it's same as other screen but the only reason this one look different is because of different boxes stages.

As can be seen in the image below, the checkbox width is same just like others.

![step-1](https://user-images.githubusercontent.com/46832636/213138248-fe00e097-9bd9-4b87-a7db-3a2c991b398c.jpg)

But since it's not producing matching result, i'll update all checkbox to be on same row like other screen to produce the screenshot below and i believe that match the spacing with other screens:

![step-2](https://user-images.githubusercontent.com/46832636/213138623-8772d2e5-802b-4e5d-a062-8ef113c017a8.jpg)
