### ISSUE TITLE
Add an explanation of each screen

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#691]
I think we need one sentence explaining what each screen does.

I wonder what the best way to do this is? Perhaps a sidebar box with a different style? 

<img width="1338" alt="Screenshot 2023-02-17 at 11 02 52 AM" src="https://user-images.githubusercontent.com/3868028/219704151-dfc4d5fc-9008-4299-b681-bc3e66c1370e.png">

Alternatively it could just be text. This is what WPForms does:
<img width="938" alt="Screenshot 2023-02-17 at 11 07 59 AM" src="https://user-images.githubusercontent.com/3868028/219705307-446d4e96-de2f-4189-a0df-407b4146be06.png">

**Comment by olatechpro** [comment]
@stevejburge We should be conclusive on the option we're going with so it doesn't end up like note that were recently removed in https://github.com/publishpress/PublishPress-Capabilities/issues/614.

Are we adding a new sidebar or we're adding description at location where notes were removed?

**Comment by stevejburge** [comment]
@olatechpro Good point. The original note wasn't that helpful. It didn't really explain things.

Let's move this for now and rethink this approach.

**Comment by olatechpro** [comment]
### From slack

**Steve:** I think the best place might be under "How to use Profile Features"

**Comment by olatechpro** [comment]
@stevejburge I didn't know how I missed this in our last conversation when you suggested the place the explanation should be added because we have discussed it before and here's my comment form  https://github.com/publishpress/PublishPress-Capabilities/issues/614#issuecomment-1396690261 which i'll paste here again.

> We're using https://github.com/publishpress/wordpress-banners package to show the right side bar content and based on the class banner method implementation, button (View documentation) is always the last item and content comes first.
> 
> So, we have three options which are:
> 
> The texts should come immediately after title (before the checkbox and button)
> We use a separate sidebar box for the text.
> Maybe modify the class to accept extra text after the button? This will work for the request and since the library is own by us, i can submit PR to https://github.com/publishpress/wordpress-banners for the changes

In summary, the text can not stay after the button because of the library we're using. 

![how to](https://user-images.githubusercontent.com/46832636/229563524-b1b38a21-e68d-461c-b114-361ba6226d27.jpg)
