### ISSUE TITLE
Admin menus feature: Some hidden / mystery links picked up

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#82]
Links
Comments 00 Comments in moderation

<img width="417" alt="Screen Shot 2020-10-15 at 4 49 16 PM" src="https://user-images.githubusercontent.com/3868028/96184686-d2747500-0f06-11eb-92d9-5b26f6bcc047.png">

Double "Background"

<img width="279" alt="Screen Shot 2020-10-15 at 4 52 41 PM" src="https://user-images.githubusercontent.com/3868028/96184846-02bc1380-0f07-11eb-8c67-14df7fcdac97.png">

Some more 0s

<img width="177" alt="Screen Shot 2020-10-15 at 4 54 47 PM" src="https://user-images.githubusercontent.com/3868028/96185093-65adaa80-0f07-11eb-9c45-a4c5c0120080.png">
<img width="149" alt="Screen Shot 2020-10-15 at 4 54 53 PM" src="https://user-images.githubusercontent.com/3868028/96185099-66ded780-0f07-11eb-9497-ec585fb4f3db.png">

**Comment by olatechpro** [comment]
Hi, basically, we process wordpress global menu.
Let me explain the each ceneria and suggestion on best alternative fix.

For the plugin, the comment array is like this:

`(
            [0] => Comments <span class="awaiting-mod count-0"><span class="pending-count" aria-hidden="true">0</span><span class="comments-in-moderation-text screen-reader-text">0 Comments in moderation</span></span>
            [1] => edit_posts
            [2] => edit-comments.php
            [3] => 
            [4] => menu-top menu-icon-comments
            [5] => menu-comments
            [6] => dashicons-admin-comments
        )`

I agree with you the reason '0 Comments in moderation' didn't show for user originally is because it's not visible due to it been screen reader text and we can strip it off as well but the count '<span class="awaiting-mod count-0"><span class="pending-count" aria-hidden="true">0</span>' is same as plugin.

`[65] => Array
        (
            [0] => Plugins <span class="update-plugins count-15"><span class="plugin-count">15</span></span>
            [1] => activate_plugins
            [2] => plugins.php
            [3] => 
            [4] => menu-top menu-icon-plugins
            [5] => menu-plugins
            [6] => dashicons-admin-plugins
        )`

which is same way it display for user except the fact the count is styles to be red in display 
![plugins](https://user-images.githubusercontent.com/46832636/96185897-87705700-0f32-11eb-9a73-556ac19017ca.png)


So, in the situations of raw names containing html tags and count apart from their initial title text, do you feel we should strip them off ?

**Comment by olatechpro** [comment]
![Uploading Screenshot 2020-10-15 at 22.08.44.png…]()

**Comment by olatechpro** [comment]
![Screenshot 2020-10-15 at 22 08 54](https://user-images.githubusercontent.com/46832636/96186279-1bdab980-0f33-11eb-8419-495e8c340f9f.png)
![Screenshot 2020-10-15 at 22 08 44](https://user-images.githubusercontent.com/46832636/96186286-1f6e4080-0f33-11eb-80f6-3261582a3560.png)
![Screenshot 2020-10-15 at 22 08 54](https://user-images.githubusercontent.com/46832636/96186290-21380400-0f33-11eb-8769-5709a95ffb0b.png)

**Comment by stevejburge** [comment]
@olatechpro Yes, let's remove them, please

**Comment by olatechpro** [comment]
> @olatechpro Yes, let's remove them, please

I'll make quick fix for it soon

**Comment by agapetry** [comment]
https://github.com/publishpress/PublishPress-Capabilities/pull/83

https://github.com/publishpress/PublishPress-Capabilities-Pro/commit/19ceb4ff80093a471248cd30135e2bd0b9440aac
