### ISSUE TITLE
Update to frontend features text and enabled colors

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#865]
Green title and message: #377E22
Yellow background: #F5CA75

Could we swap these for other colors used in the plugin?

<img width="592" alt="Screenshot 2023-07-24 at 9 28 19 AM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/829c1c7d-03af-4813-8348-d442f54a7f86">

**Comment by olatechpro** [comment]
@stevejburge can you screenshot the color they should be replaced with?

**Comment by stevejburge** [comment]
@olatechpro Could we just use the colors on the normal "Posts" screen. 

For example, on the background, alternate rows of #fff and #F6F7F7

**Comment by stevejburge** [comment]
@olatechpro Can we use #5ECD8A whenever we mean good / enabled success

In other cases like this we don't need green. "test2" can be a normal title style. The code area could be PublishPress purple:
#655997
<img width="567" alt="Screenshot 2023-07-24 at 8 05 53 PM" src="https://github.com/publishpress/PublishPress-Capabilities/assets/3868028/6ddaac90-9154-4282-9fe4-1e6c628f7b58">

**Comment by olatechpro** [comment]
@stevejburge I marked the area in your screenshot 1, 2 and 3 since those are 3 areas with green color. Can you match the color provided for each area.

Example: 
1 = #5ECD8A
2 = #5ECD8A
3 = #655997

Also, are we removing the yellow color for new items?

<img width="567" alt="255767286-6ddaac90-9154-4282-9fe4-1e6c628f7b58" src="https://github.com/publishpress/PublishPress-Capabilities/assets/46832636/0baa0c85-f34e-48a3-914a-a0d342d57dac">

**Comment by stevejburge** [comment]
Sure thing @olatechpro 

1. No change
2. #3071A5
3. #3071A5 or #655997
