### ISSUE TITLE
Fix the PublishPress capabilities

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Capabilities#88]
These are not quite right:

- "ppma edit orphan post" has been dropped
- "status change" is not thing, I don't think
- "edit pp notif workflow" and others are not included

<img width="987" alt="Screen Shot 2020-10-23 at 4 57 41 PM" src="https://user-images.githubusercontent.com/3868028/97053476-06781780-1551-11eb-82a9-2bd374d15fd5.png">

**Comment by stevejburge** [comment]
@agapetry Sure, works for me

**Comment by agapetry** [comment]
I'm also going to review the Invalid Capabilities section.  It's reporting too many false positives.  To me, the main value of the section is to clue users in that if they have assigned "edit_post", that won't give the expected results because that's only an internal code placeholder for "whatever post editing capabilities the requested post requires."  I'll try to clarify this better.

**Comment by agapetry** [comment]
Okay, I see that Capabilities needs to display assigned (or plugin-registered) read / edit / delete meta capabilities in the Invalid section only if map_meta_cap is enabled for the post type.

**Comment by agapetry** [comment]
@andergmartins Was there an intentional decision to register the pp_notif_workflow post type without map_meta_cap?  Are there situations where you want a literal "edit_pp_notif_workflow" capability check instead of "edit_pp_notif_workflows" ?
